export const PRODUCTS_ACTION_TYPES = {
    FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
    FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
    FETCH_PRODUCT_FAILURE: "FETCH_PRODUCT_FAILURE",
    SET_SELECTED_PRODUCT: "SET_SELECTED_PRODUCT",
    ADD_NEW_PRODUCT: "ADD_NEW_PRODUCT",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",
  };
  