export const ORDERSS_ACTION_TYPES = {
  CHANGE_ORDER_STATUS: 'CHANGE_ORDER_STATUS',
  FETCH_ORDER_START: "FETCH_ORDER_START",
  FETCH_ORDER_SUCCESS: "FETCH_ORDER_SUCCESS",
  FETCH_ORDER_FAILURE: "FETCH_ORDER_FAILURE",
  SET_SELECTED_ORDER: "SET_SELECTED_ORDER",
};